name: excash
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  sqflite: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.8.3
  image_picker: ^1.0.8
  qr_code_scanner: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  file_picker: ^8.0.0+1
  fl_chart: ^0.62.0
  shared_preferences: ^2.2.3
  blue_thermal_printer: ^1.2.3
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
  - assets/img/gagal.png
  - assets/img/sukses.png
  - assets/img/excash_logo.png
  - assets/img/auth.png
  - assets/img/excash_logo_hitam.png
  - assets/img/profile.png

  